# Title of your blog; shows in the header
name: "toplayoutguide"

# Description of your content (will only be used on Google Search)
description: "A fun Swift programming blog. By an Australian iOS Engineer in Tokyo."

# Your name. Will show in your footer + sidebar
author: "Benjamin Deckys"

url: "http://toplayoutguide.github.io"
baseurl: "/"

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I'm an Aussie iOS Engineer, living in Tokyo. I use Xcode to develop things. I play around with SwiftUI too, pet any Dogs I can, and enjoy drinking coffee. Lastly, this is my blog! How about we close this here side panel and enjoy some code?"

# Social Accounts

twitter: viewdidappear
github: toplayoutguide
instagram: okokokjeez

# Other

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed