# Title of your blog; shows in the header
title: "viewDidAppear()"
description: "A blog about Swift, and Swift-related happenings in my life."
email: blog@ggggg.wtf
permalink:      /:year-:month-:day/:title

# Description of your content (will only be used on Google Search)
description: "A fun Swift programming blog. By an Australian iOS Engineer in Tokyo."

# Your name. Will show in your footer + sidebar
author: "Benjamin Deckys"

url: "http://viewdidappear.github.io"
baseurl: ""

# Social Accounts

twitter: viewdidappear
github: viewdidappear
instagram: okokokjeez

# Other

markdown: kramdown
include:
  - _pages
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

paginate: 5
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _sass
  style: :compressed

# Author settings
author:
  - name: "viewDidAppear()"
    bio: "I play with Xcode and make things, and I relocated from Melbourne, Australia to Tokyo, Japan in 2018. Past workplaces include jtribe apps, WeTV iflix and Mercari Inc, but now I'm a Senior iOS Software Engineer at PayPay Corporation."
    url: 

# Build Settings

exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
